---
include:
  - board: levels54_left
    snippet: nrf52840-nosd
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_SETTINGS_RESET_ON_START
  - board: levels54_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_SETTINGS_RESET_ON_START
# build.yaml example
  - board: seeeduino_xiao_ble
    shield: levels54_dongle prospector_adapter
  - board: levels54_left
    snippet: nrf52840-nosd
    shield: settings_reset
  - board: levels54_right
    shield: settings_reset
# build.yaml example

  
