---
include:
  - board: levels54_left
    # Wipe all ZMK settings (NVS). Disable split so the wipe image is tiny and avoids split references.
    cmake-args: -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y -DCONFIG_ZMK_SPLIT=n
  - board: levels54_right
    # Wipe ZMK settings and also clear any stored BLE bonds on first boot.
    cmake-args: -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y -DCONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y -DCONFIG_ZMK_SPLIT=n
