---
include:
  - board: levels54_left
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_STUDIO=n -DCONFIG_USB_DEVICE_STACK=n
  - board: levels54_right
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_STUDIO=n -DCONFIG_USB_DEVICE_STACK=n
